apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: kube-system
data:
  cancel.rules: |
    groups:
    - name: ts-cancel-service相关接口QPS下降
      rules:
      - alert: calculate接口QPS下降
        expr: sum(rate(ts_cancel_calculate_seconds_count[5m])) == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "实例{{ $labels.instance }}上的服务{{ $labels.service }}的calculate接口QPS跌0"
      - alert: cancelTicket接口QPS下降
        expr: sum(rate(ts_cancel_cancelTicket_seconds_count[5m])) == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "实例{{ $labels.instance }}上的服务{{ $labels.service }}的cancelTicket接口QPS跌0"