apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: kube-system
data:
  contacts.rules: |
    groups:
    - name: ts-contacts-service相关接口QPS下降
      rules:
      - alert: findContactsByAccountId接口QPS下降
        expr: sum(rate(ts_contacts_findContactsByAccountId_seconds_count[5m])) == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "实例{{ $labels.instance }}上的服务{{ $labels.service }}的findContactsByAccountId接口QPS跌0"
      - alert: createNewContacts接口QPS下降
        expr: sum(rate(ts_contacts_createNewContacts_seconds_count[5m])) == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "实例{{ $labels.instance }}上的服务{{ $labels.service }}的createNewContacts接口QPS跌0"