apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: kube-system
data:
  food.rules: |
    groups:
    - name: ts-food-service相关接口QPS下降
      rules:
      - alert: getAllFood接口QPS下降
        expr: sum(rate(ts_food_getAllFood_seconds_count[5m])) == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "实例{{ $labels.instance }}上的服务{{ $labels.service }}的getAllFood接口QPS跌0"