apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: kube-system
data:
  insidePayment.rules: |
    groups:
    - name: 支付成功量下降告警
      rules:
      - alert: 支付成功量下降告警
        expr: sum(rate(ts_inside_payment_pay_seconds_count[5m])) < 0.5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: 5min内支付成功量增长率低于0.5