apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-template
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  email.tmpl: |
    {{ define "email.to.html" }}
    {{ range .Alerts }}
    <p>==========<strong>告警通知</strong>==========</p>
    <strong>告警程序:</strong> kubernetes-service-endpoints<br>
    <strong>告警名称:</strong> {{ .Labels.alertname }} <br>
    <strong>告警内容:</strong> {{ .Annotations.summary }} <br>
    <strong>告警级别:</strong> {{ .Labels.severity }} <br>
    <strong>故障实例:</strong> 10.244.4.3:14568<br>
    <strong>触发时间:</strong> {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }} <br>
    <strong>监控界面地址:</strong> <a href="{{ .GeneratorURL }}">点击跳转</a>
    {{ end }}
    {{ end }}