apiVersion: v1
kind: Service
metadata:
  name: ts-admin-basic-info-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "18767"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 18767
  selector:
    app: ts-admin-basic-info-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-admin-order-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "16112"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 16112
  selector:
    app: ts-admin-order-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-admin-route-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "16113"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 16113
  selector:
    app: ts-admin-route-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-admin-travel-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "16114"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 16114
  selector:
    app: ts-admin-travel-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-admin-user-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "16115"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 16115
  selector:
    app: ts-admin-user-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-assurance-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "18888"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 18888
  selector:
    app: ts-assurance-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-auth-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "12340"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 12340
  selector:
    app: ts-auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-avatar-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "17001"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 17001
  selector:
    app: ts-avatar-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-basic-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "15680"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 15680
  selector:
    app: ts-basic-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-cancel-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "18885"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 18885
  selector:
    app: ts-cancel-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-config-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "15679"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 15679
  selector:
    app: ts-config-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-consign-price-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "16110"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 16110
  selector:
    app: ts-consign-price-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-consign-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "16111"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 16111
  selector:
    app: ts-consign-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-contacts-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "12347"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 12347
  selector:
    app: ts-contacts-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-delivery-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "18808"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 18808
  selector:
    app: ts-delivery-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-execute-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "12386"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 12386
  selector:
    app: ts-execute-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-food-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "18856"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 18856
  selector:
    app: ts-food-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-gateway-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "18888"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 18888
      nodePort: 30467
  selector:
    app: ts-gateway-service
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ts-inside-payment-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "18673"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 18673
  selector:
    app: ts-inside-payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-news-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "12862"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 12862
  selector:
    app: ts-news-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-notification-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "17853"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 17853
  selector:
    app: ts-notification-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-order-other-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "12032"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 12032
  selector:
    app: ts-order-other-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-order-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "12031"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 12031
  selector:
    app: ts-order-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-payment-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "19001"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 19001
  selector:
    app: ts-payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-preserve-other-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "14569"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 14569
  selector:
    app: ts-preserve-other-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-preserve-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "14568"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 14568
  selector:
    app: ts-preserve-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-price-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "16579"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 16579
  selector:
    app: ts-price-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-rebook-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "18886"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 18886
  selector:
    app: ts-rebook-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-route-plan-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "14578"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 14578
  selector:
    app: ts-route-plan-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-route-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "11178"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 11178
  selector:
    app: ts-route-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-seat-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "18898"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 18898
  selector:
    app: ts-seat-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-security-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "11188"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 11188
  selector:
    app: ts-security-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-station-food-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "18855"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 18855
  selector:
    app: ts-station-food-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-station-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "12345"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 12345
  selector:
    app: ts-station-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-ticket-office-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "16108"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 16108
  selector:
    app: ts-ticket-office-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-train-food-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "19999"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 19999
  selector:
    app: ts-train-food-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-train-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "14567"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 14567
  selector:
    app: ts-train-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-travel-plan-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "14322"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 14322
  selector:
    app: ts-travel-plan-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-travel-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "12346"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 12346
  selector:
    app: ts-travel-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-travel2-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "16346"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 16346
  selector:
    app: ts-travel2-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-user-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "12342"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 12342
  selector:
    app: ts-user-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-verification-code-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "15678"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 15678
  selector:
    app: ts-verification-code-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-voucher-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "16101"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 16101
  selector:
    app: ts-voucher-service
---
apiVersion: v1
kind: Service
metadata:
  name: ts-ui-dashboard
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 32677
  selector:
    app: ts-ui-dashboard