apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    # otelcol的地址
    endpoint: http://47.103.205.96:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
